version: '3.8'

services:
    database:
        image: postgres
        environment:
            POSTGRES_USER: tekken
            POSTGRES_PASSWORD: space
            POSTGRES_DB: dev
        ports:
            - "5432:5432"
        volumes:
            - ./var/tekken/database:/var/lib/postgresql/data

    frontend:
        image: rherwig/tekken-space-frontend:latest
        restart: "unless-stopped"
        depends_on:
            - database
        volumes:
            - /var/tekken/frontend/.env:/app/apps/frontend/.env

    proxy:
        image: rherwig/tekken-space-proxy:latest
        restart: "always"
        volumes:
            - /var/tekken/proxy:/data
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
