version: '3.8'

services:
    tekken-app:
        build: .
        restart: "unless-stopped"
        depends_on:
            - database
        volumes:
            - /var/hrwg/portier/.env:/app/apps/portier/.env

    database:
        image: mongo:6.0.5
        container_name: tekken-database
        restart: "unless-stopped"
        ports:
            - "27017:27017"
        volumes:
            - ./var/data:/data/db
