version: '3.8'

services:
    frontend:
        image: rherwig/tekken-space-frontend:latest
        restart: "unless-stopped"
        depends_on:
            - database
        volumes:
            - /var/tekken/frontend/.env:/app/apps/frontend/.env

    database:
        image: rherwig/tekken-space-database:latest
        container_name: tekken-database
        restart: "unless-stopped"
        volumes:
            - /var/tekken/data:/data/db

    proxy:
        image: rherwig/tekken-space-proxy:latest
        restart: "always"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
