-- AlterTable
ALTER TABLE "Move" ADD COLUMN     "blockFrames" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "counterHitFrames" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "hasTailspin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hitFrames" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "isHoming" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isPowerCrush" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isWallBounce" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "startupFrames" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
